package com.qlvt.enums;

public enum ChatIntent {
    SEARCH_MATERIAL,
    CHECK_STOCK,
    CHECK_LOCATION,
    CHECK_EXPIRY,
    CHECK_BATCH,
    CHECK_SUPPLIER,
    SUGGEST_ALTERNATIVE,
    CHECK_REQUEST_STATUS,
    CREATE_REQUEST_DRAFT,
    HELP_CREATE_REQUEST,
    CHECK_RECEIVED_HISTORY,
    CHECK_DEPARTMENT_EXPIRING_MATERIALS,
    CHECK_DEPARTMENT_STOCK,
    HELP,
    UNKNOWN
}
