package com.qlvt.enums;

public enum ChatIntent {
    ASK_STOCK,
    ASK_LOCATION,
    ASK_EXPIRY,
    ASK_IMPORT_DATE,
    ASK_BATCH,
    ASK_LOW_STOCK,
    ASK_EXPIRED_OR_NEAR_EXPIRED,
    ASK_RECOMMEND_ISSUE,
    GENERAL_HELP,
    SEARCH_MATERIAL,
    CHECK_STOCK,
    CHECK_LOCATION,
    CHECK_EXPIRY,
    CHECK_BATCH,
    CHECK_SUPPLIER,
    SUGGEST_ALTERNATIVE,
    CHECK_REQUEST_STATUS,
    CREATE_REQUEST_DRAFT,
    HELP_CREATE_REQUEST,
    CHECK_RECEIVED_HISTORY,
    CHECK_DEPARTMENT_EXPIRING_MATERIALS,
    CHECK_DEPARTMENT_STOCK,
    HELP,
    UNKNOWN
}
