spring.application.name=qlvt
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${PORT:8080}

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.error.include-message=always
server.error.whitelabel.enabled=false

app.upload.dir=uploads
app.upload.max-file-size=10485760
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB
